[project]
name = "open_learning_ai_tutor"
version = "0.0.0"
description = "AI powered tutor"
authors = [
    { name = "MIT Open Learning Engineering", email = "odl-devops@mit.edu" }
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["README.md", "**/*.py"]
exclude = ["BUILD", "pyproject.toml", "app.py"]

[tool.hatch.build.targets.wheel]
include = ["README.md", "**/*.py"]
exclude = ["BUILD", "pyproject.toml", "app.py"]